// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPI_CRUD.Models;

#nullable disable

namespace WebAPI_CRUD.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250925175904_First_migration")]
    partial class First_migration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebAPI_CRUD.Models.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5e6c90db-0b2c-427f-b7b6-2b93298dd307"),
                            Name = "IT"
                        },
                        new
                        {
                            Id = new Guid("02c3be5b-7d30-4113-bce3-a8e5693ca858"),
                            Name = "HR"
                        },
                        new
                        {
                            Id = new Guid("a8507b28-e2b7-457a-bb8b-ec15f1871d79"),
                            Name = "Finance"
                        });
                });

            modelBuilder.Entity("WebAPI_CRUD.Models.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e851ec9f-5bc9-4304-9654-9dde451201a4"),
                            DateOfBirth = new DateOnly(1994, 12, 2),
                            DepartmentId = new Guid("5e6c90db-0b2c-427f-b7b6-2b93298dd307"),
                            Email = "Ram.Kumar@gmail.com",
                            FirstName = "Ram",
                            Gender = 0,
                            LastName = "Kumar"
                        },
                        new
                        {
                            Id = new Guid("308ce876-7545-45fd-af67-a5856d681b16"),
                            DateOfBirth = new DateOnly(1998, 2, 23),
                            DepartmentId = new Guid("02c3be5b-7d30-4113-bce3-a8e5693ca858"),
                            Email = "Sham.Patil@gmail.com",
                            FirstName = "Sham",
                            Gender = 0,
                            LastName = "Patil"
                        },
                        new
                        {
                            Id = new Guid("fddf90ca-b08a-4f35-aced-338c37827f18"),
                            DateOfBirth = new DateOnly(1999, 3, 17),
                            DepartmentId = new Guid("02c3be5b-7d30-4113-bce3-a8e5693ca858"),
                            Email = "Asha.Bhosale@gmail.com",
                            FirstName = "Asha",
                            Gender = 1,
                            LastName = "Bhosale"
                        },
                        new
                        {
                            Id = new Guid("674f6969-995f-49bd-b2b3-60156681e181"),
                            DateOfBirth = new DateOnly(1990, 10, 10),
                            DepartmentId = new Guid("5e6c90db-0b2c-427f-b7b6-2b93298dd307"),
                            Email = "Lata.Mangeshkar@gmail.com",
                            FirstName = "Lata",
                            Gender = 1,
                            LastName = "Mangeshkar"
                        });
                });

            modelBuilder.Entity("WebAPI_CRUD.Models.Employee", b =>
                {
                    b.HasOne("WebAPI_CRUD.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });
#pragma warning restore 612, 618
        }
    }
}
